# Generated by Django 5.0.6 on 2024-06-25 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coopApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='about',
            field=models.CharField(default='DEFAULT VALUE', max_length=40),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='age',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='citizenship',
            field=models.CharField(default='DEFAULT VALUE', max_length=40),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='contacts',
            field=models.CharField(default='DEFAULT VALUE', max_length=40),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='education',
            field=models.CharField(default='DEFAULT VALUE', max_length=40),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='exp',
            field=models.CharField(default='DEFAULT VALUE', max_length=40),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='ifOnlineWork',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='location',
            field=models.CharField(default='DEFAULT VALUE', max_length=40),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='photo',
            field=models.ImageField(default='DEFAULT VALUE', upload_to=''),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='salary',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='skills',
            field=models.CharField(default='DEFAULT VALUE', max_length=40),
        ),
    ]
