# Generated by Django 5.0.6 on 2024-06-25 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coopApp', '0002_portfolio_about_portfolio_age_portfolio_citizenship_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='ifOnlineWork',
            field=models.CharField(default='DEFAULT VALUE', max_length=40),
        ),
    ]
