# Generated by Django 5.0.6 on 2024-07-10 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coopApp', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='idToPort',
            field=models.CharField(default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.CharField(default='anonym', max_length=50),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.CharField(default='none', max_length=15),
        ),
        migrations.AlterField(
            model_name='comment',
            name='ref',
            field=models.CharField(default='none', max_length=10),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='comment',
            name='verified',
            field=models.CharField(default='verificated', max_length=20),
        ),
    ]
