# Generated by Django 5.0.7 on 2024-07-14 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coopApp', '0006_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='photo',
        ),
    ]
