# Generated by Django 5.0.7 on 2024-08-05 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coopApp', '0007_remove_portfolio_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='about',
            field=models.CharField(default='DEFAULT VALUE', max_length=500),
        ),
    ]
