# Generated by Django 5.0.7 on 2024-10-16 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coopApp', '0008_alter_portfolio_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='citizenship',
            new_name='mail',
        ),
        migrations.RenameField(
            model_name='portfolio',
            old_name='contacts',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='ifOnlineWork',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='hobby',
            field=models.CharField(default='DEFAULT VALUE', max_length=100),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='languages',
            field=models.CharField(default='DEFAULT VALUE', max_length=100),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='userName',
            field=models.CharField(default='DEFAULT VALUE', max_length=20),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='education',
            field=models.CharField(default='DEFAULT VALUE', max_length=200),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='exp',
            field=models.CharField(default='DEFAULT VALUE', max_length=400),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='name',
            field=models.CharField(default='DEFAULT VALUE', max_length=20),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='occupation',
            field=models.CharField(default='DEFAULT VALUE', max_length=200),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='skills',
            field=models.CharField(default='DEFAULT VALUE', max_length=400),
        ),
    ]
