# Generated by Django 5.0.7 on 2024-10-16 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coopApp', '0009_rename_citizenship_portfolio_mail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='com',
            field=models.CharField(default='DEFAULT VALUE', max_length=40),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='sch',
            field=models.CharField(default='DEFAULT VALUE', max_length=40),
        ),
    ]
