# Generated by Django 5.0.7 on 2024-10-16 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coopApp', '0010_portfolio_com_portfolio_sch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='salary',
        ),
    ]
