# Generated by Django 5.0.7 on 2024-10-16 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coopApp', '0011_remove_portfolio_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='salary',
            field=models.CharField(default='DEFAULT VALUE', max_length=20),
        ),
    ]
