# Generated by Django 5.0.7 on 2024-10-16 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coopApp', '0012_portfolio_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='age',
            field=models.CharField(default='DEFAULT VALUE', max_length=20),
        ),
    ]
